import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="bg-gray-950 text-white">
        <nav className="border-b border-gray-800 p-4">
          <div className="container mx-auto flex items-center justify-between">
            <a href="/" className="text-xl font-bold">Wallzen</a>
            <div className="space-x-4">
              <a href="/latest" className="hover:text-gray-300">Latest</a>
              <a href="/popular" className="hover:text-gray-300">Popular</a>
            </div>
          </div>
        </nav>
        {children}
      </body>
    </html>
  )
}
